/* js/gallery/artworks.js
   Purpose : the list of artworks (file name, title, category) shown in the gallery preview, modal and lightbox.
   Owns    : the `artworks` array. Artworks are identified by FILE NAME everywhere (never by index).
   Uses    : nothing.   Used by: gallery.gallery (and, through a legacy alias in script.js, the botanical "seed of curiosity" art pool).
   Mobile / reduced motion: not applicable (data).
   Moved verbatim from script.js (Migration Step 3a). Image files live in images/ (GitHub Pages is case-sensitive: keep these names exact, e.g. mandala.PNG). */
MB.define('gallery.artworks', [], function () {
    'use strict';

    const artworks = [
        {file:'mandala_passion.png',title:'Passion',category:'mandala'},{file:'mandala_multicolor.jpg',title:'Multicolor Mandala',category:'mandala'},{file:'mandala_bw.png',title:'Black & White',category:'mandala'},{file:'mandala.PNG',title:'Intricate Mandala',category:'mandala'},{file:'purplemandala.jpg',title:'Purple Mandala',category:'mandala'},{file:'mandala_blue.jpg',title:'Blue Mandala',category:'mandala'},{file:'mandala_green.jpg',title:'Teal Mandala',category:'mandala'},{file:'mandala_pink.jpg',title:'Pink Mandala',category:'mandala'},{file:'mandala_darkpink.jpg',title:'Hot Pink Mandala',category:'mandala'},{file:'mandala_orange.jpg',title:'Orange Mandala',category:'mandala'},{file:'mandala_yellow.jpg',title:'Yellow Mandala',category:'mandala'},{file:'mandala_circle.jpg',title:'Circle Mandala',category:'mandala'},{file:'mandala_w2.jpg',title:'Dual Mandala',category:'mandala'},
        {file:'Tulips.jpg',title:'Tulips',category:'digital'},{file:'Untitled_Artwork_27.jpg',title:'Sweet Treats',category:'digital'},{file:'Untitled_Artwork_26.jpg',title:'Kitty Loops',category:'digital'},{file:'cute_cat_ditigal_art.jpg',title:'Cereal-ously a Catch',category:'digital'},{file:'Untitled_Artwork_22.jpg',title:'Polaroid Cameras',category:'digital'},{file:'Untitled_Artwork_21.jpg',title:'Sunset Frame Purple',category:'digital'},{file:'Untitled_Artwork_20_copy.jpg',title:'Sunset Frame Warm',category:'digital'},{file:'Send_noods_2.jpg',title:'Send Noods',category:'digital'},{file:'Science_2.jpg',title:'Science Potions',category:'digital'},{file:'Roses.jpg',title:'Roses',category:'digital'},{file:'Little_prince_2.jpg',title:'Little Prince Rose',category:'digital'},{file:'Letter_2.jpg',title:'Flower Letter',category:'digital'},{file:'Gelato_.jpg',title:'Gelato at Yale',category:'digital'},{file:'Flower_Book_Open.jpg',title:'Flower Book',category:'digital'},{file:'Eggs_2.jpg',title:'Eggcellent',category:'digital'},{file:'Dog_hamburger_2.jpg',title:'Dog Burger',category:'digital'},{file:'Corgi__2.jpg',title:'Corgi Ice Cream',category:'digital'},{file:'Cinabunny_2.jpg',title:'Cinabunny',category:'digital'},{file:'Cat.jpg',title:'Reading Cat',category:'digital'},{file:'Cake.jpg',title:'Birthday Cake',category:'digital'},{file:'madeinchina.jpg',title:'Made in China',category:'digital'},
        {file:'calligraphy.jpg',title:'Kathleen',category:'calligraphy'},{file:'calligraphy1.jpg',title:'Maryam',category:'calligraphy'},{file:'calligraphy2.jpg',title:'Rise',category:'calligraphy'},{file:'calligraphy3.jpg',title:'Thank You',category:'calligraphy'},{file:'calligraphy4.jpg',title:'Mom Card',category:'calligraphy'},{file:'calligraphy5.jpg',title:'Thinking of You',category:'calligraphy'},{file:'calligraphy6.jpg',title:'Robin',category:'calligraphy'},{file:'card_mandala.jpg',title:'Mandala Card',category:'calligraphy'},{file:'card_flowers.jpg',title:'You Are Amazing',category:'calligraphy'},{file:'cards.jpg',title:'Handmade Cards',category:'calligraphy'},{file:'bday_card.jpg',title:'Birthday Card',category:'calligraphy'},
        {file:'face_full_of_stars.png',title:'Face Full of Stars',category:'fineart'},{file:'eyeswithcolors.jpg',title:'Colorful Eyes',category:'fineart'},{file:'peonies.png',title:'Peonies',category:'fineart'},{file:'mirror.jpg',title:'Broken Mirror',category:'fineart'},{file:'sunflowers.jpg',title:'Sunflowers',category:'fineart'},{file:'Reader.jpg',title:'The Reader',category:'fineart'},{file:'Books_Stacked.jpg',title:'Books Stacked',category:'fineart'},{file:'statueface.jpg',title:'Classical Statue',category:'fineart'},{file:'mybodyasnature.jpg',title:'My Body As Nature',category:'fineart'}
    ];

    return { artworks };
});
